repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      exclude: ^tests/.*/data/.*$
    - id: end-of-file-fixer
      exclude:  ^tests/.*/data/.*$
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
    - id: cmake-format
#    - id: cmake-lint
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint
    args: [-f]
